# Generated by Django 3.1.8 on 2021-05-26 09:39

from django.db import migrations, models
import django.db.models.deletion
import sections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(max_length=30, null=True)),
                ('about_text', models.TextField(null=True)),
                ('display_picture', models.ImageField(upload_to='dp')),
                ('person_name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(default='Sample', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('mobile_number', models.CharField(default='09xxxxxxxxx', max_length=15)),
                ('email', models.CharField(default='youremail@gmail.com', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(max_length=30, null=True)),
                ('small_text', models.CharField(blank=True, max_length=10, null=True)),
                ('large_text', models.CharField(blank=True, max_length=10, null=True)),
                ('career_title', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='JSChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(default='Sample', max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('description', models.CharField(default='Description here', max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='project-preview-images')),
                ('website_link', models.CharField(blank=True, default='www.website.com', max_length=30, null=True)),
                ('github_link', models.CharField(blank=True, default='github.com/user/repo', max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='TechStackImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sections.models.tech_stack_images_path)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack_images', to='sections.project')),
            ],
        ),
    ]
