# Generated by Django 3.1.8 on 2021-06-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20210609_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechStack',
        ),
    ]
